import type {
  Contractor,
  Project,
  Review,
  KycSubmission,
  AuditLog,
  PlatformMetrics,
  AuthUser,
  Bid,
} from '@/types';

export const mockContractors: Contractor[] = [
  {
    id: 'c1',
    userId: 'u-conn-1',
    businessName: 'Aarav BuildWorks',
    ownerName: 'Rajesh Kumar',
    bio: 'Civil contractor focused on new home construction, RCC structure execution, and end-to-end site supervision for residential projects.',
    location: 'Gurugram, Haryana',
    specializations: ['New Home Construction', 'Civil Construction', 'Structural Work', 'Masonry'],
    rating: 4.9,
    reviewCount: 132,
    projectsCompleted: 226,
    hourlyRate: 1900,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0d1ef5d0d2fc?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&h=400&fit=crop',
    verified: true,
    aiRecommended: true,
    yearsActive: 16,
  },
  {
    id: 'c2',
    userId: 'u-conn-2',
    businessName: 'Sharma Construction & Interiors',
    ownerName: 'Priya Mehta',
    bio: 'Interior and renovation specialist for modular kitchens, bathroom upgrades, and turnkey apartment remodeling.',
    location: 'Chandigarh, Punjab',
    specializations: ['Home Renovation', 'Interior Design', 'Modular Kitchen', 'Bathroom Renovation'],
    rating: 4.8,
    reviewCount: 104,
    projectsCompleted: 171,
    hourlyRate: 60,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=400&fit=crop',
    verified: true,
    aiRecommended: true,
    yearsActive: 11,
  },
  {
    id: 'c3',
    userId: 'u-conn-3',
    businessName: 'Verma Civil Works',
    ownerName: 'Vikram Singh',
    bio: 'Site execution team for foundation, waterproofing, plaster, and complete civil packages for villas and independent homes.',
    location: 'Panipat, Haryana',
    specializations: ['Civil Construction', 'Waterproofing', 'Masonry', 'Home Renovation'],
    rating: 4.7,
    reviewCount: 161,
    projectsCompleted: 245,
    hourlyRate: 1750,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 14,
  },
  {
    id: 'c4',
    userId: 'u-conn-4',
    businessName: 'GharDesign Studio',
    ownerName: 'Neha Kapoor',
    bio: 'Design-led contractor for interiors, false ceiling, lighting plans, and premium finish execution for urban homes.',
    location: 'Noida, Uttar Pradesh',
    specializations: ['Interior Design', 'False Ceiling', 'Flooring', 'Painting'],
    rating: 4.8,
    reviewCount: 86,
    projectsCompleted: 141,
    hourlyRate: 65,
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1416874593199-d9a1c5c0c2f0?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 8,
  },
  {
    id: 'c5',
    userId: 'u-conn-5',
    businessName: 'PrimeBuild Contractors',
    ownerName: 'Rohit Verma',
    bio: 'General contractor with dedicated teams for electrical, plumbing, carpentry, and finishing for medium to large projects.',
    location: 'Delhi NCR',
    specializations: ['New Home Construction', 'Electrical Work', 'Plumbing', 'Carpentry'],
    rating: 4.9,
    reviewCount: 119,
    projectsCompleted: 198,
    hourlyRate: 1850,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45305?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 13,
  },
  {
    id: 'c6',
    userId: 'u-conn-6',
    businessName: 'UrbanNest Contractors',
    ownerName: 'Manish Gupta',
    bio: 'Execution-focused team for home renovation, tile and flooring work, bathroom upgrades, and plumbing packages.',
    location: 'Pune, Maharashtra',
    specializations: ['Home Renovation', 'Bathroom Renovation', 'Flooring', 'Plumbing'],
    rating: 4.6,
    reviewCount: 138,
    projectsCompleted: 229,
    hourlyRate: 1500,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1581244277913-9f8760d2e9c0?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 15,
  },
  {
    id: 'c7',
    userId: 'u-conn-7',
    businessName: 'BuildCraft India',
    ownerName: 'Aarav Sharma',
    bio: 'Finishing contractor for painting, fabrication, aluminium and glass work with strong focus on on-time delivery.',
    location: 'Ahmedabad, Gujarat',
    specializations: ['Painting', 'Fabrication', 'Aluminium & Glass Work'],
    rating: 4.7,
    reviewCount: 94,
    projectsCompleted: 153,
    hourlyRate: 800,
    avatarUrl: 'https://images.unsplash.com/photo-1507591064344-4ce6b8e9c8a3?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1562259949-5c8e95e6c4be?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 9,
  },
  {
    id: 'c8',
    userId: 'u-conn-8',
    businessName: 'Singh Infra & Structures',
    ownerName: 'Vikrant Singh',
    bio: 'Contractor for structural additions, waterproofing, external civil work, and turnkey villa shell construction.',
    location: 'Jaipur, Rajasthan',
    specializations: ['Structural Work', 'Waterproofing', 'Civil Construction', 'New Home Construction'],
    rating: 4.8,
    reviewCount: 109,
    projectsCompleted: 184,
    hourlyRate: 1800,
    avatarUrl: 'https://images.unsplash.com/photo-1633333072494-d3c2c5e0e1a3?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1558618666fcd6c8a6e9c8b0?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 12,
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    clientId: 'u-client-1',
    clientName: 'Rahul Sharma',
    contractorId: 'c1',
    contractorName: 'Aarav BuildWorks',
    title: 'New G+1 Home Construction',
    description: 'End-to-end construction of a 2-floor independent home with RCC frame, electrical, plumbing, and finishing.',
    category: 'New Home Construction',
    status: 'IN_PROGRESS',
    budget: 2500000,
    startDate: '2026-06-15',
    estimatedEndDate: '2027-01-10',
    location: 'Gurugram, Haryana',
    progress: 52,
    milestones: [
      { id: 'm1', title: 'Site Preparation', description: 'Boundary setup, site cleaning, and marking completed', status: 'COMPLETED', dueDate: '2026-06-25', amount: 200000, completedDate: '2026-06-23' },
      { id: 'm2', title: 'Foundation', description: 'Excavation, PCC, footing, and plinth beam completed', status: 'COMPLETED', dueDate: '2026-07-25', amount: 450000, completedDate: '2026-07-24' },
      { id: 'm3', title: 'RCC Structure', description: 'Columns, slab, staircase and core structural work in progress', status: 'IN_PROGRESS', dueDate: '2026-09-15', amount: 700000 },
      { id: 'm4', title: 'Brickwork, Plumbing and Electrical', description: 'Internal walling and utility line routing', status: 'PENDING', dueDate: '2026-11-10', amount: 600000 },
      { id: 'm5', title: 'Plastering, Flooring and Finishing', description: 'Final finishing and handover preparation', status: 'PENDING', dueDate: '2027-01-05', amount: 550000 },
    ],
  },
  {
    id: 'p2',
    clientId: 'u-client-1',
    clientName: 'Rahul Sharma',
    contractorId: 'c2',
    contractorName: 'Sharma Construction & Interiors',
    title: 'Modular Kitchen & Living Renovation',
    description: 'Kitchen redesign with modular units, false ceiling, and flooring updates for living and dining areas.',
    category: 'Home Renovation',
    status: 'AWAITING_REVIEW',
    budget: 850000,
    startDate: '2026-07-01',
    estimatedEndDate: '2026-09-30',
    location: 'Noida, Uttar Pradesh',
    progress: 90,
    milestones: [
      { id: 'm1', title: 'Demolition & Site Protection', description: 'Removal of old fixtures with controlled site protection', status: 'COMPLETED', dueDate: '2026-07-05', amount: 90000, completedDate: '2026-07-04' },
      { id: 'm2', title: 'Electrical & Plumbing', description: 'New utility routing for kitchen and utility points', status: 'COMPLETED', dueDate: '2026-07-22', amount: 150000, completedDate: '2026-07-21' },
      { id: 'm3', title: 'Modular Installation', description: 'Cabinet, granite and hardware installation', status: 'COMPLETED', dueDate: '2026-08-30', amount: 360000, completedDate: '2026-08-29' },
      { id: 'm4', title: 'Flooring & Paint', description: 'Flooring finishing and final paint coats', status: 'COMPLETED', dueDate: '2026-09-15', amount: 130000, completedDate: '2026-09-14' },
      { id: 'm5', title: 'Final Handover', description: 'Snag resolution and project handover', status: 'IN_PROGRESS', dueDate: '2026-09-28', amount: 120000 },
    ],
  },
  {
    id: 'p3',
    clientId: 'u-client-2',
    clientName: 'Priya Gupta',
    contractorId: 'c1',
    contractorName: 'Aarav BuildWorks',
    title: 'Ground Floor Extension',
    description: 'Civil extension for one bedroom and utility area with masonry, plastering, and flooring.',
    category: 'Home Renovation',
    status: 'REQUESTED',
    budget: 1200000,
    startDate: '2026-09-01',
    estimatedEndDate: '2026-12-10',
    location: 'Lucknow, Uttar Pradesh',
    progress: 0,
    milestones: [
      { id: 'm1', title: 'Design Freeze', description: 'Layout and structural changes finalised', status: 'PENDING', dueDate: '2026-09-08', amount: 120000 },
      { id: 'm2', title: 'Foundation & Masonry', description: 'Footing and wall construction', status: 'PENDING', dueDate: '2026-10-10', amount: 420000 },
      { id: 'm3', title: 'Electrical & Plumbing', description: 'Concealed wiring and plumbing lines', status: 'PENDING', dueDate: '2026-11-05', amount: 260000 },
      { id: 'm4', title: 'Flooring & Finishing', description: 'Tile, paint and fit-out handover', status: 'PENDING', dueDate: '2026-12-05', amount: 400000 },
    ],
  },
  {
    id: 'p4',
    clientId: 'u-client-3',
    clientName: 'Amit Verma',
    contractorId: 'c3',
    contractorName: 'Verma Civil Works',
    title: 'Bathroom and Plumbing Upgrade',
    description: 'Two-bathroom renovation with waterproofing, tile replacement, sanitary fitting, and plumbing line corrections.',
    category: 'Bathroom Renovation',
    status: 'COMPLETED',
    budget: 450000,
    startDate: '2026-05-10',
    estimatedEndDate: '2026-06-07',
    location: 'Panipat, Haryana',
    progress: 100,
    milestones: [
      { id: 'm1', title: 'Demolition & Dismantling', description: 'Removal of old fixtures and damaged plumbing lines', status: 'COMPLETED', dueDate: '2026-05-15', amount: 70000, completedDate: '2026-05-15' },
      { id: 'm2', title: 'Waterproofing & Plumbing', description: 'Waterproofing membrane and pipe work completed', status: 'COMPLETED', dueDate: '2026-05-28', amount: 180000, completedDate: '2026-05-27' },
      { id: 'm3', title: 'Tiling & Finishing', description: 'Tile installation, sanitary fitting, final checks', status: 'COMPLETED', dueDate: '2026-06-06', amount: 200000, completedDate: '2026-06-06' },
    ],
  },
  {
    id: 'p5',
    clientId: 'u-client-4',
    clientName: 'Neha Malhotra',
    contractorId: 'c5',
    contractorName: 'PrimeBuild Contractors',
    title: 'Electrical Rewiring & Panel Upgrade',
    description: 'Complete electrical rewiring for 3BHK with distribution board, safety breakers, and final load testing.',
    category: 'Electrical Work',
    status: 'ACCEPTED',
    budget: 300000,
    startDate: '2026-08-20',
    estimatedEndDate: '2026-09-02',
    location: 'Mumbai, Maharashtra',
    progress: 0,
    milestones: [
      { id: 'm1', title: 'Circuit Mapping & Safety Audit', description: 'Electrical point mapping and material confirmation', status: 'PENDING', dueDate: '2026-08-22', amount: 70000 },
      { id: 'm2', title: 'Rewiring & Panel Setup', description: 'New wiring, DB installation, and earthing checks', status: 'PENDING', dueDate: '2026-08-29', amount: 150000 },
      { id: 'm3', title: 'Final Fittings & Testing', description: 'Switchboard fitting and final testing', status: 'PENDING', dueDate: '2026-09-01', amount: 80000 },
    ],
  },
];

export const mockBids: Bid[] = [
  {
    id: 'b1',
    projectId: 'p3',
    contractorId: 'c1',
    amount: 1450000,
    estimatedDays: 75,
    message: 'We can complete the ground floor extension with our masonry and finishing teams.',
    status: 'ACCEPTED',
    project: { title: 'Ground Floor Extension', status: 'REQUESTED', location: 'Lucknow, Uttar Pradesh', budget: 1200000 },
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'b2',
    projectId: 'p1',
    contractorId: 'c1',
    amount: 2320000,
    estimatedDays: 120,
    message: 'Revised structural estimate with dedicated site supervisor and milestone billing.',
    status: 'PENDING',
    project: { title: 'New G+1 Home Construction', status: 'IN_PROGRESS', location: 'Gurugram, Haryana', budget: 2500000 },
    createdAt: '2026-08-18T09:30:00Z',
  },
  {
    id: 'b3',
    projectId: 'p2',
    contractorId: 'c2',
    amount: 820000,
    estimatedDays: 60,
    message: 'Turnkey renovation quote for modular kitchen and living area.',
    status: 'ACCEPTED',
    project: { title: 'Modular Kitchen & Living Renovation', status: 'AWAITING_REVIEW', location: 'Noida, Uttar Pradesh', budget: 850000 },
    createdAt: '2026-08-12T14:15:00Z',
  },
];

export const mockReviews: Review[] = [
  { id: 'r1', projectId: 'p4', contractorId: 'c3', clientName: 'Amit Verma', rating: 5, comment: 'Clear scope, quality work, and milestone-based tracking helped us finish our renovation with confidence.', date: '2026-05-20' },
  { id: 'r2', projectId: 'p1', contractorId: 'c1', clientName: 'Rahul Sharma', rating: 5, comment: 'We could track structural progress, labour, and costs from one place. Execution quality has been very strong.', date: '2026-08-05' },
  { id: 'r3', projectId: 'p2', contractorId: 'c2', clientName: 'Priya Gupta', rating: 4, comment: 'The estimate and milestone planning gave us realistic expectations for budget and timeline.', date: '2026-07-28' },
  { id: 'r4', projectId: 'p3', contractorId: 'c4', clientName: 'Neha Malhotra', rating: 5, comment: 'Professional team and transparent communication throughout design and execution.', date: '2026-06-01' },
  { id: 'r5', projectId: 'p5', contractorId: 'c5', clientName: 'Sanjay Arora', rating: 5, comment: 'Electrical work was completed on time and the safety checks were clearly documented.', date: '2026-05-30' },
];

export const mockKycSubmissions: KycSubmission[] = [
  {
    id: 'k1',
    contractorId: 'c7',
    contractorName: 'Aarav Sharma',
    businessName: 'BuildCraft India',
    email: 'aarav@buildcraftindia.in',
    status: 'PENDING',
    submittedAt: '2026-08-08T14:30:00Z',
    businessAddress: 'Sector 14, Gurugram, Haryana 122001',
    taxId: '27ABCDE1234F1Z9',
    licenseNumber: 'HR-CON-459812',
    documents: [
      { id: 'd1', type: 'ID_PROOF', fileName: 'aadhaar_card.pdf', fileUrl: '#', uploadedAt: '2026-08-08T14:25:00Z' },
      { id: 'd2', type: 'LICENSE', fileName: 'contractor_license.pdf', fileUrl: '#', uploadedAt: '2026-08-08T14:26:00Z' },
      { id: 'd3', type: 'INSURANCE', fileName: 'liability_insurance_cert.pdf', fileUrl: '#', uploadedAt: '2026-08-08T14:28:00Z' },
    ],
  },
  {
    id: 'k2',
    contractorId: 'u-conn-9',
    contractorName: 'Neha Kapoor',
    businessName: 'GharDesign Studio',
    email: 'neha@ghardesignstudio.in',
    status: 'PENDING',
    submittedAt: '2026-08-10T09:15:00Z',
    businessAddress: 'Sector 62, Noida, Uttar Pradesh 201309',
    taxId: '06AAAPL9032Q1ZF',
    licenseNumber: 'UP-INT-332105',
    documents: [
      { id: 'd4', type: 'ID_PROOF', fileName: 'pan_card_scan.pdf', fileUrl: '#', uploadedAt: '2026-08-10T09:10:00Z' },
      { id: 'd5', type: 'LICENSE', fileName: 'trade_license.pdf', fileUrl: '#', uploadedAt: '2026-08-10T09:12:00Z' },
      { id: 'd6', type: 'BUSINESS_REGISTRATION', fileName: 'llc_articles.pdf', fileUrl: '#', uploadedAt: '2026-08-10T09:14:00Z' },
    ],
  },
  {
    id: 'k3',
    contractorId: 'u-conn-10',
    contractorName: 'Rohit Verma',
    businessName: 'PrimeBuild Contractors',
    email: 'rohit@primebuildcontractors.in',
    status: 'PENDING',
    submittedAt: '2026-08-09T16:45:00Z',
    businessAddress: 'Dwarka, Delhi NCR 110075',
    taxId: '07AAECP4408K1ZT',
    licenseNumber: 'DL-CIV-902114',
    documents: [
      { id: 'd7', type: 'ID_PROOF', fileName: 'voter_id.pdf', fileUrl: '#', uploadedAt: '2026-08-09T16:40:00Z' },
      { id: 'd8', type: 'LICENSE', fileName: 'builder_registration.pdf', fileUrl: '#', uploadedAt: '2026-08-09T16:42:00Z' },
      { id: 'd9', type: 'INSURANCE', fileName: 'workers_comp.pdf', fileUrl: '#', uploadedAt: '2026-08-09T16:44:00Z' },
    ],
  },
];

export const mockAuditLogs: AuditLog[] = [
  { id: 'a1', userId: 'u-admin-1', userName: 'admin@gharmate.in', action: 'KYC_APPROVED', resource: 'kyc/k1', timestamp: '2026-08-10T15:30:00Z', ipAddress: '192.168.1.100', status: 'SUCCESS', details: 'Approved KYC for BuildCraft India' },
  { id: 'a2', userId: 'u-client-1', userName: 'rahul@gharmate.in', action: 'BOOKING_CREATED', resource: 'project/p3', timestamp: '2026-08-10T14:22:00Z', ipAddress: '103.78.22.110', status: 'SUCCESS', details: 'Created project request: Ground Floor Extension' },
  { id: 'a3', userId: 'u-conn-1', userName: 'rajesh@aaravbuildworks.in', action: 'MILESTONE_UPDATED', resource: 'project/p1/milestone/m3', timestamp: '2026-08-10T13:15:00Z', ipAddress: '122.176.91.20', status: 'SUCCESS', details: 'Started milestone: RCC Structure' },
  { id: 'a4', userId: 'u-unknown', userName: 'unknown@email.com', action: 'LOGIN_FAILED', resource: 'auth/login', timestamp: '2026-08-10T12:01:00Z', ipAddress: '45.227.100.34', status: 'FAILED', details: 'Invalid credentials, 3rd attempt' },
  { id: 'a5', userId: 'u-admin-1', userName: 'admin@gharmate.in', action: 'USER_BLOCKED', resource: 'user/u-spam-1', timestamp: '2026-08-10T11:45:00Z', ipAddress: '192.168.1.100', status: 'SUCCESS', details: 'Blocked user for spam listings' },
  { id: 'a6', userId: 'u-client-2', userName: 'priya@gharmate.in', action: 'DOCUMENT_UPLOADED', resource: 'project/p3/docs', timestamp: '2026-08-10T10:30:00Z', ipAddress: '49.36.110.77', status: 'SUCCESS', details: 'Uploaded site_layout_plan.pdf' },
  { id: 'a7', userId: 'u-conn-2', userName: 'priya@sharmaconstruction.in', action: 'BOOKING_ACCEPTED', resource: 'project/p2', timestamp: '2026-08-09T16:00:00Z', ipAddress: '122.160.8.44', status: 'SUCCESS', details: 'Accepted project: Modular Kitchen & Living Renovation' },
  { id: 'a8', userId: 'u-admin-1', userName: 'admin@gharmate.in', action: 'KYC_REJECTED', resource: 'kyc/k0', timestamp: '2026-08-09T14:10:00Z', ipAddress: '192.168.1.100', status: 'WARNING', details: 'Rejected KYC: expired license document' },
  { id: 'a9', userId: 'u-client-1', userName: 'rahul@gharmate.in', action: 'REVIEW_SUBMITTED', resource: 'review/r1', timestamp: '2026-08-08T09:00:00Z', ipAddress: '103.78.22.110', status: 'SUCCESS', details: 'Submitted 5-star review for Verma Civil Works' },
  { id: 'a10', userId: 'u-conn-3', userName: 'vikram@vermacivilworks.in', action: 'PROJECT_COMPLETED', resource: 'project/p4', timestamp: '2026-08-07T17:30:00Z', ipAddress: '106.51.82.191', status: 'SUCCESS', details: 'Marked project as completed' },
];

export const mockMetrics: PlatformMetrics = {
  totalUsers: 4827,
  activeProjects: 342,
  pendingKycs: 3,
  totalRevenue: 12845000,
  totalContractors: 1184,
  totalClients: 3643,
  verifiedContractors: 892,
  monthlyGrowth: 18.4,
};

export const mockUsers: AuthUser[] = [
  { id: 'u-client-1', email: 'rahul@gharmate.in', fullName: 'Rahul Sharma', role: 'ROLE_CLIENT', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop' },
  { id: 'u-conn-1', email: 'rajesh@aaravbuildworks.in', fullName: 'Rajesh Kumar', role: 'ROLE_CONTRACTOR', kycStatus: 'APPROVED', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0d1ef5d0d2fc?w=200&h=200&fit=crop' },
  { id: 'u-admin-1', email: 'admin@gharmate.in', fullName: 'System Admin', role: 'ROLE_ADMIN', avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop' },
];

export const allSpecializations = [
  'Civil Construction',
  'New Home Construction',
  'Home Renovation',
  'Interior Design',
  'Modular Kitchen',
  'Bathroom Renovation',
  'Electrical Work',
  'Plumbing',
  'Painting',
  'Carpentry',
  'Flooring',
  'False Ceiling',
  'Waterproofing',
  'Masonry',
  'Structural Work',
  'Aluminium & Glass Work',
  'Fabrication',
  'Landscaping',
];

export const allLocations = [
  'Delhi NCR',
  'Gurugram, Haryana',
  'Noida, Uttar Pradesh',
  'Chandigarh, Punjab',
  'Mohali, Punjab',
  'Jaipur, Rajasthan',
  'Bengaluru, Karnataka',
  'Mumbai, Maharashtra',
  'Hyderabad, Telangana',
  'Pune, Maharashtra',
  'Chennai, Tamil Nadu',
  'Ahmedabad, Gujarat',
  'Kolkata, West Bengal',
  'Lucknow, Uttar Pradesh',
  'Amritsar, Punjab',
  'Ludhiana, Punjab',
  'Panipat, Haryana',
  'Karnal, Haryana',
  'Hisar, Haryana',
  'Ambala, Haryana',
];
