import type {
  Contractor,
  Project,
  Review,
  KycSubmission,
  AuditLog,
  PlatformMetrics,
  AuthUser,
} from '@/types';

export const mockContractors: Contractor[] = [
  {
    id: 'c1',
    userId: 'u-conn-1',
    businessName: 'Summit Ridge Builders',
    ownerName: 'Marcus Thornton',
    bio: 'Award-winning residential contractor specializing in custom home builds, major renovations, and structural work. 18 years serving the greater metro area.',
    location: 'Denver, CO',
    specializations: ['General Contracting', 'Home Addition', 'Foundation', 'Framing'],
    rating: 4.9,
    reviewCount: 127,
    projectsCompleted: 214,
    hourlyRate: 95,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0d1ef5d0d2fc?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&h=400&fit=crop',
    verified: true,
    aiRecommended: true,
    yearsActive: 18,
  },
  {
    id: 'c2',
    userId: 'u-conn-2',
    businessName: 'Lumina Kitchen & Bath',
    ownerName: 'Sofia Chen',
    bio: 'Premium kitchen and bathroom remodeling. We handle everything from design to final inspection with a focus on modern, functional spaces.',
    location: 'Austin, TX',
    specializations: ['Kitchen Remodel', 'Bathroom Remodel', 'Cabinetry', 'Tile'],
    rating: 4.8,
    reviewCount: 89,
    projectsCompleted: 156,
    hourlyRate: 85,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=400&fit=crop',
    verified: true,
    aiRecommended: true,
    yearsActive: 12,
  },
  {
    id: 'c3',
    userId: 'u-conn-3',
    businessName: 'Ironwood Roofing Co.',
    ownerName: 'James Okafor',
    bio: 'Family-owned roofing company. Full roof replacements, repairs, and inspections. Licensed and insured across three states.',
    location: 'Phoenix, AZ',
    specializations: ['Roofing', 'Gutters', 'Insulation', 'Siding'],
    rating: 4.7,
    reviewCount: 203,
    projectsCompleted: 389,
    hourlyRate: 75,
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 22,
  },
  {
    id: 'c4',
    userId: 'u-conn-4',
    businessName: 'Verde Landscape & Design',
    ownerName: 'Elena Vasquez',
    bio: 'Full-service landscaping and outdoor living. From hardscaping to irrigation, we create outdoor spaces you will love for years.',
    location: 'San Diego, CA',
    specializations: ['Landscaping', 'Hardscaping', 'Patio', 'Outdoor Kitchen'],
    rating: 4.8,
    reviewCount: 64,
    projectsCompleted: 98,
    hourlyRate: 70,
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1416874593199-d9a1c5c0c2f0?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 9,
  },
  {
    id: 'c5',
    userId: 'u-conn-5',
    businessName: 'Brightline Electrical',
    ownerName: 'David Park',
    bio: 'Licensed electrician for residential and light commercial. Panel upgrades, rewiring, smart home installation, and EV charger setup.',
    location: 'Seattle, WA',
    specializations: ['Electrical', 'Smart Home', 'EV Charger', 'Panel Upgrade'],
    rating: 4.9,
    reviewCount: 51,
    projectsCompleted: 87,
    hourlyRate: 90,
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45305?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 11,
  },
  {
    id: 'c6',
    userId: 'u-conn-6',
    businessName: 'Coastline Plumbing & Heating',
    ownerName: 'Rachel Donovan',
    bio: 'Plumbing and HVAC services. Repairs, installations, tankless water heaters, and emergency service available 24/7.',
    location: 'Boston, MA',
    specializations: ['Plumbing', 'HVAC', 'Water Heater', 'Radiant Heating'],
    rating: 4.6,
    reviewCount: 142,
    projectsCompleted: 276,
    hourlyRate: 80,
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1581244277913-9f8760d2e9c0?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 15,
  },
  {
    id: 'c7',
    userId: 'u-conn-7',
    businessName: 'Mason & Co. Painting',
    ownerName: 'Tony Mason',
    bio: 'Interior and exterior painting specialists. Cabinet refinishing, drywall repair, and wallpaper installation.',
    location: 'Portland, OR',
    specializations: ['Painting', 'Drywall', 'Cabinet Refinishing'],
    rating: 4.7,
    reviewCount: 78,
    projectsCompleted: 134,
    hourlyRate: 55,
    avatarUrl: 'https://images.unsplash.com/photo-1507591064344-4ce6b8e9c8a3?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1562259949-5c8e95e6c4be?w=800&h=400&fit=crop',
    verified: false,
    yearsActive: 7,
  },
  {
    id: 'c8',
    userId: 'u-conn-8',
    businessName: 'Apex Flooring Solutions',
    ownerName: 'Kwame Asante',
    bio: 'Hardwood, tile, laminate, and vinyl flooring installation. Dust-free sanding and refinishing for existing floors.',
    location: 'Atlanta, GA',
    specializations: ['Flooring', 'Hardwood', 'Tile', 'Refinishing'],
    rating: 4.8,
    reviewCount: 96,
    projectsCompleted: 167,
    hourlyRate: 65,
    avatarUrl: 'https://images.unsplash.com/photo-1633333072494-d3c2c5e0e1a3?w=200&h=200&fit=crop',
    coverUrl: 'https://images.unsplash.com/photo-1558618666fcd6c8a6e9c8b0?w=800&h=400&fit=crop',
    verified: true,
    yearsActive: 10,
  },
];

export const mockProjects: Project[] = [
  {
    id: 'p1',
    clientId: 'u-client-1',
    clientName: 'Jordan Blake',
    contractorId: 'c1',
    contractorName: 'Summit Ridge Builders',
    title: 'Master Suite Addition',
    description: 'Adding a 400 sq ft master suite with en-suite bathroom and walk-in closet above the existing garage.',
    category: 'Home Addition',
    status: 'IN_PROGRESS',
    budget: 85000,
    startDate: '2026-06-15',
    estimatedEndDate: '2026-10-30',
    location: 'Denver, CO',
    progress: 45,
    milestones: [
      { id: 'm1', title: 'Permits & Design Finalization', description: 'Architectural plans approved and city permits obtained', status: 'COMPLETED', dueDate: '2026-06-20', amount: 15000, completedDate: '2026-06-18' },
      { id: 'm2', title: 'Foundation & Framing', description: 'Foundation poured, framing and roof tie-in complete', status: 'COMPLETED', dueDate: '2026-07-30', amount: 25000, completedDate: '2026-07-28' },
      { id: 'm3', title: 'Electrical, Plumbing & HVAC Rough-in', description: 'All rough-ins inspected and approved', status: 'IN_PROGRESS', dueDate: '2026-08-25', amount: 20000 },
      { id: 'm4', title: 'Insulation & Drywall', description: 'Insulation installed, drywall hung and finished', status: 'PENDING', dueDate: '2026-09-20', amount: 15000 },
      { id: 'm5', title: 'Finish Work & Final Inspection', description: 'Flooring, trim, paint, final inspection and walkthrough', status: 'PENDING', dueDate: '2026-10-28', amount: 10000 },
    ],
  },
  {
    id: 'p2',
    clientId: 'u-client-1',
    clientName: 'Jordan Blake',
    contractorId: 'c2',
    contractorName: 'Lumina Kitchen & Bath',
    title: 'Modern Kitchen Renovation',
    description: 'Full gut renovation of kitchen with new cabinets, quartz countertops, island, and stainless appliances.',
    category: 'Kitchen Remodel',
    status: 'AWAITING_REVIEW',
    budget: 42000,
    startDate: '2026-07-01',
    estimatedEndDate: '2026-09-15',
    location: 'Denver, CO',
    progress: 90,
    milestones: [
      { id: 'm1', title: 'Demolition & Disposal', description: 'Old kitchen removed and disposed', status: 'COMPLETED', dueDate: '2026-07-05', amount: 5000, completedDate: '2026-07-04' },
      { id: 'm2', title: 'Electrical & Plumbing Rough-in', description: 'Updated wiring and plumbing for new layout', status: 'COMPLETED', dueDate: '2026-07-20', amount: 8000, completedDate: '2026-07-18' },
      { id: 'm3', title: 'Cabinetry & Countertops', description: 'Custom cabinets installed, quartz fabricated and set', status: 'COMPLETED', dueDate: '2026-08-15', amount: 18000, completedDate: '2026-08-14' },
      { id: 'm4', title: 'Tile Backsplash & Flooring', description: 'Backsplash and luxury vinyl plank flooring', status: 'COMPLETED', dueDate: '2026-08-30', amount: 6000, completedDate: '2026-08-28' },
      { id: 'm5', title: 'Final Punch List & Walkthrough', description: 'Appliance install, paint, final walkthrough', status: 'IN_PROGRESS', dueDate: '2026-09-14', amount: 5000 },
    ],
  },
  {
    id: 'p3',
    clientId: 'u-client-2',
    clientName: 'Priya Sharma',
    contractorId: 'c1',
    contractorName: 'Summit Ridge Builders',
    title: 'Deck & Pergola Build',
    description: '20x12 composite deck with cedar pergola and integrated lighting.',
    category: 'Outdoor Living',
    status: 'REQUESTED',
    budget: 18000,
    startDate: '2026-09-01',
    estimatedEndDate: '2026-10-15',
    location: 'Boulder, CO',
    progress: 0,
    milestones: [
      { id: 'm1', title: 'Design & Permits', description: 'Finalize design and obtain permits', status: 'PENDING', dueDate: '2026-09-05', amount: 2000 },
      { id: 'm2', title: 'Framing & Structure', description: 'Deck framing, posts, and beam structure', status: 'PENDING', dueDate: '2026-09-20', amount: 8000 },
      { id: 'm3', title: 'Decking & Railing', description: 'Composite decking boards and railing', status: 'PENDING', dueDate: '2026-10-05', amount: 5000 },
      { id: 'm4', title: 'Pergola & Finishing', description: 'Pergola construction, lighting, stain', status: 'PENDING', dueDate: '2026-10-14', amount: 3000 },
    ],
  },
  {
    id: 'p4',
    clientId: 'u-client-3',
    clientName: 'Tom Wilson',
    contractorId: 'c3',
    contractorName: 'Ironwood Roofing Co.',
    title: 'Full Roof Replacement',
    description: 'Tear off existing asphalt shingles and install new architectural shingles with underlayment and ice guard.',
    category: 'Roofing',
    status: 'COMPLETED',
    budget: 12500,
    startDate: '2026-05-10',
    estimatedEndDate: '2026-05-17',
    location: 'Phoenix, AZ',
    progress: 100,
    milestones: [
      { id: 'm1', title: 'Tear-off & Inspection', description: 'Old roof removed, deck inspected', status: 'COMPLETED', dueDate: '2026-05-11', amount: 3000, completedDate: '2026-05-11' },
      { id: 'm2', title: 'Underlayment & Shingles', description: 'Ice guard, underlayment, and shingle install', status: 'COMPLETED', dueDate: '2026-05-15', amount: 7500, completedDate: '2026-05-14' },
      { id: 'm3', title: 'Cleanup & Final Inspection', description: 'Site cleanup, final inspection passed', status: 'COMPLETED', dueDate: '2026-05-17', amount: 2000, completedDate: '2026-05-17' },
    ],
  },
  {
    id: 'p5',
    clientId: 'u-client-4',
    clientName: 'Sarah Klein',
    contractorId: 'c5',
    contractorName: 'Brightline Electrical',
    title: 'EV Charger & Panel Upgrade',
    description: 'Upgrade to 200A panel and install Level 2 EV charger in garage.',
    category: 'Electrical',
    status: 'ACCEPTED',
    budget: 4500,
    startDate: '2026-08-20',
    estimatedEndDate: '2026-08-23',
    location: 'Seattle, WA',
    progress: 0,
    milestones: [
      { id: 'm1', title: 'Panel Upgrade', description: 'Replace 100A panel with 200A', status: 'PENDING', dueDate: '2026-08-21', amount: 2500 },
      { id: 'm2', title: 'EV Charger Install', description: 'Install and test Level 2 charger', status: 'PENDING', dueDate: '2026-08-23', amount: 2000 },
    ],
  },
];

export const mockReviews: Review[] = [
  { id: 'r1', projectId: 'p4', contractorId: 'c3', clientName: 'Tom Wilson', rating: 5, comment: 'Ironwood was fast, professional, and cleaned up perfectly. Roof looks great and the crew was on time every day.', date: '2026-05-20' },
  { id: 'r2', projectId: 'p-completed-1', contractorId: 'c1', clientName: 'Amanda Reyes', rating: 5, comment: 'Marcus and his team built our entire guest house. Communication was excellent and the quality is top-notch.', date: '2026-04-15' },
  { id: 'r3', projectId: 'p-completed-2', contractorId: 'c2', clientName: 'Brian Lee', rating: 4, comment: 'Beautiful kitchen transformation. A few delays but the end result exceeded expectations.', date: '2026-03-22' },
  { id: 'r4', projectId: 'p-completed-3', contractorId: 'c4', clientName: 'Nina Patel', rating: 5, comment: 'Elena redesigned our backyard and it is now our favorite room in the house. Highly recommend Verde!', date: '2026-06-01' },
  { id: 'r5', projectId: 'p-completed-4', contractorId: 'c5', clientName: 'Greg Hopper', rating: 5, comment: 'David upgraded our panel and installed two EV chargers. Clean work, fair price, and great communication.', date: '2026-05-30' },
];

export const mockKycSubmissions: KycSubmission[] = [
  {
    id: 'k1',
    contractorId: 'c7',
    contractorName: 'Tony Mason',
    businessName: 'Mason & Co. Painting',
    email: 'tony@masoncopainting.com',
    status: 'PENDING',
    submittedAt: '2026-08-08T14:30:00Z',
    businessAddress: '1422 SE Holgate Blvd, Portland, OR 97202',
    taxId: 'XX-XXX4521',
    licenseNumber: 'OR-CCB-228941',
    documents: [
      { id: 'd1', type: 'ID_PROOF', fileName: 'drivers_license_front.pdf', fileUrl: '#', uploadedAt: '2026-08-08T14:25:00Z' },
      { id: 'd2', type: 'LICENSE', fileName: 'ccb_license.pdf', fileUrl: '#', uploadedAt: '2026-08-08T14:26:00Z' },
      { id: 'd3', type: 'INSURANCE', fileName: 'liability_insurance_cert.pdf', fileUrl: '#', uploadedAt: '2026-08-08T14:28:00Z' },
    ],
  },
  {
    id: 'k2',
    contractorId: 'u-conn-9',
    contractorName: 'Lisa Tran',
    businessName: 'Tran Interiors & Design',
    email: 'lisa@traninteriors.com',
    status: 'PENDING',
    submittedAt: '2026-08-10T09:15:00Z',
    businessAddress: '88 Pine St, San Francisco, CA 94102',
    taxId: 'XX-XXX8830',
    licenseNumber: 'CA-CSLB-1024456',
    documents: [
      { id: 'd4', type: 'ID_PROOF', fileName: 'passport_scan.pdf', fileUrl: '#', uploadedAt: '2026-08-10T09:10:00Z' },
      { id: 'd5', type: 'LICENSE', fileName: 'cslb_license.pdf', fileUrl: '#', uploadedAt: '2026-08-10T09:12:00Z' },
      { id: 'd6', type: 'BUSINESS_REGISTRATION', fileName: 'llc_articles.pdf', fileUrl: '#', uploadedAt: '2026-08-10T09:14:00Z' },
    ],
  },
  {
    id: 'k3',
    contractorId: 'u-conn-10',
    contractorName: 'Roberto Silva',
    businessName: 'Silva Concrete & Masonry',
    email: 'roberto@silvaconcrete.com',
    status: 'PENDING',
    submittedAt: '2026-08-09T16:45:00Z',
    businessAddress: '350 Industrial Pkwy, Dallas, TX 75207',
    taxId: 'XX-XXX2209',
    licenseNumber: 'TX-TDLR-RC-345890',
    documents: [
      { id: 'd7', type: 'ID_PROOF', fileName: 'state_id.pdf', fileUrl: '#', uploadedAt: '2026-08-09T16:40:00Z' },
      { id: 'd8', type: 'LICENSE', fileName: 'tdlr_license.pdf', fileUrl: '#', uploadedAt: '2026-08-09T16:42:00Z' },
      { id: 'd9', type: 'INSURANCE', fileName: 'workers_comp.pdf', fileUrl: '#', uploadedAt: '2026-08-09T16:44:00Z' },
    ],
  },
];

export const mockAuditLogs: AuditLog[] = [
  { id: 'a1', userId: 'u-admin-1', userName: 'admin@buildbond.com', action: 'KYC_APPROVED', resource: 'kyc/k1', timestamp: '2026-08-10T15:30:00Z', ipAddress: '192.168.1.100', status: 'SUCCESS', details: 'Approved KYC for Mason & Co. Painting' },
  { id: 'a2', userId: 'u-client-1', userName: 'jordan@email.com', action: 'BOOKING_CREATED', resource: 'project/p3', timestamp: '2026-08-10T14:22:00Z', ipAddress: '73.221.45.90', status: 'SUCCESS', details: 'Created project request: Deck & Pergola Build' },
  { id: 'a3', userId: 'u-conn-1', userName: 'marcus@summitridge.com', action: 'MILESTONE_UPDATED', resource: 'project/p1/milestone/m3', timestamp: '2026-08-10T13:15:00Z', ipAddress: '68.4.22.180', status: 'SUCCESS', details: 'Started milestone: Electrical, Plumbing & HVAC Rough-in' },
  { id: 'a4', userId: 'u-unknown', userName: 'unknown@email.com', action: 'LOGIN_FAILED', resource: 'auth/login', timestamp: '2026-08-10T12:01:00Z', ipAddress: '45.227.100.34', status: 'FAILED', details: 'Invalid credentials, 3rd attempt' },
  { id: 'a5', userId: 'u-admin-1', userName: 'admin@buildbond.com', action: 'USER_BLOCKED', resource: 'user/u-spam-1', timestamp: '2026-08-10T11:45:00Z', ipAddress: '192.168.1.100', status: 'SUCCESS', details: 'Blocked user for spam listings' },
  { id: 'a6', userId: 'u-client-2', userName: 'priya@email.com', action: 'DOCUMENT_UPLOADED', resource: 'project/p3/docs', timestamp: '2026-08-10T10:30:00Z', ipAddress: '73.221.45.91', status: 'SUCCESS', details: 'Uploaded site_survey.pdf' },
  { id: 'a7', userId: 'u-conn-2', userName: 'sofia@luminakb.com', action: 'BOOKING_ACCEPTED', resource: 'project/p2', timestamp: '2026-08-09T16:00:00Z', ipAddress: '68.4.22.181', status: 'SUCCESS', details: 'Accepted project: Modern Kitchen Renovation' },
  { id: 'a8', userId: 'u-admin-1', userName: 'admin@buildbond.com', action: 'KYC_REJECTED', resource: 'kyc/k0', timestamp: '2026-08-09T14:10:00Z', ipAddress: '192.168.1.100', status: 'WARNING', details: 'Rejected KYC: expired license document' },
  { id: 'a9', userId: 'u-client-1', userName: 'jordan@email.com', action: 'REVIEW_SUBMITTED', resource: 'review/r1', timestamp: '2026-08-08T09:00:00Z', ipAddress: '73.221.45.90', status: 'SUCCESS', details: 'Submitted 5-star review for Ironwood Roofing' },
  { id: 'a10', userId: 'u-conn-3', userName: 'james@ironwoodroofing.com', action: 'PROJECT_COMPLETED', resource: 'project/p4', timestamp: '2026-08-07T17:30:00Z', ipAddress: '68.4.22.182', status: 'SUCCESS', details: 'Marked project as completed' },
];

export const mockMetrics: PlatformMetrics = {
  totalUsers: 4827,
  activeProjects: 342,
  pendingKycs: 3,
  totalRevenue: 12845000,
  totalContractors: 1184,
  totalClients: 3643,
  verifiedContractors: 892,
  monthlyGrowth: 18.4,
};

export const mockUsers: AuthUser[] = [
  { id: 'u-client-1', email: 'jordan@email.com', fullName: 'Jordan Blake', role: 'ROLE_CLIENT', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop' },
  { id: 'u-conn-1', email: 'marcus@summitridge.com', fullName: 'Marcus Thornton', role: 'ROLE_CONTRACTOR', kycStatus: 'APPROVED', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0d1ef5d0d2fc?w=200&h=200&fit=crop' },
  { id: 'u-admin-1', email: 'admin@buildbond.com', fullName: 'System Admin', role: 'ROLE_ADMIN', avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop' },
];

export const allSpecializations = [
  'General Contracting',
  'Kitchen Remodel',
  'Bathroom Remodel',
  'Roofing',
  'Electrical',
  'Plumbing',
  'HVAC',
  'Flooring',
  'Landscaping',
  'Painting',
  'Home Addition',
  'Foundation',
  'Siding',
  'Smart Home',
  'Outdoor Kitchen',
];

export const allLocations = [
  'Denver, CO',
  'Austin, TX',
  'Phoenix, AZ',
  'San Diego, CA',
  'Seattle, WA',
  'Boston, MA',
  'Portland, OR',
  'Atlanta, GA',
];
